# Generated by Django 5.1.6 on 2025-02-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_name_review_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default='randomemail@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
