# Generated by Django 5.1.6 on 2025-03-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modelling_data',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
