# Generated by Django 5.1.6 on 2025-03-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_modelling_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modelling_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
